#!/bin/bash
if [ "$1" == "dist-upgrade" ]; then
    PACKAGES=$(apt list --upgradable | tail +2 | cut -d/ -f1 | tr '\r\n' ' ')
else
    PACKAGES="$1"
fi

echo '--------------------- Reloading Debian repository ---------------------'
cp /etc/apt/sources.list.debian /etc/apt/sources.list
apt update

echo '--------------------- Removing old downloaded packages ---------------------'
rm -rf /root/debs/*

echo '--------------------- Downloading packages ---------------------'
cd /root/debs
apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests \
  --no-conflicts --no-breaks --no-replaces --no-enhances \
  --no-pre-depends ${PACKAGES} | grep "^\w")

echo '--------------------- Generate packages meta ---------------------'
dpkg-scanpackages -m . > Packages
dpkg-scanpackages -m . | gzip > Packages.gz

echo '--------------------- Reloading local repository ---------------------'
cp /etc/apt/sources.list.local /etc/apt/sources.list
apt update

echo '--------------------- Syncing Private repository ---------------------'
aptly repo add debian /root/debs

echo '--------------------- Fix owner ---------------------'
chown -R www-data:www-data /var/www/aptly
